-name: deploy-hotstar-clone
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ DOCKER_HUB_USERNAME }}/hotstar-clone:latest
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ SSH.REMOTE_HOST }}
          username: ${{ SSH.REMOTE_USER }}
          key: ${{ SSH.REMOTE_SSH_KEY }}
          port: ${{ SSH.REMOTE_PORT }}
          script: |
            docker pull ${{ DOCKER_HUB_USERNAME }}/hotstar-clone:latest
            docker stop hotstar-clone || true
            docker rm hotstar-clone || true
            docker run -d -p 3000:80 --name hotstar-clone ${{ DOCKER_HUB_USERNAME }}/hotstar-clone:latest     